### ISSUE TITLE
Seeing some of javax.crypto.BadPaddingException: pad block corrupted

### ISSUE THREAD

**Issue by shimitapiro** [sveinungkb/encrypted-userprefs#1]
com.app.utils.SecurePreferences$SecurePreferencesException: javax.crypto.BadPaddingException: pad block corrupted
at com.app.utils.SecurePreferences.convert(SecurePreferences.java:193)
at com.app.utils.SecurePreferences.decrypt(SecurePreferences.java:179)
at com.app.utils.SecurePreferences.getString(SecurePreferences.java:136)

Any idea why ?
Thanks 
Shimi

**Comment by Benjamin1333** [comment]
Same here. Really annoying

**Comment by mnr-moustafa** [comment]
Any updates here please?

**Comment by oshamahue** [comment]
I think I figured out the problem. I was using the secure preferences with dagger as a singleton in a multi threaded env. making the getString and putValue methods synchronized solves the problem.
